spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pruebaplantilla
    username: postgres
    password: root
    
  profiles:
    active: dev
      
# JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:  
        jdbc.lob.non_contextual_creation: true
        
security:
 jwt:
  token:
   secret-key: secret-key
   expire-length: 99999999
